import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";

// redux
import StoreProvider from "./store/storeProvider";

const monoSans = Mona_Sans({
  variable: "--font-mono-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Unsplash App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monoSans.className}`}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
