import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";

// Redux
import StoreProvider from "./store/storeProvider";

// Components
import AuthWrapper from "./components/AuthWrapper";
import { ToastContainer } from "react-toastify";

const monoSans = Mona_Sans({
  variable: "--font-mono-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Unsplash App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monoSans.className}`}>
        <StoreProvider>
          <AuthWrapper>{children}</AuthWrapper>
          <ToastContainer position="bottom-right" />
        </StoreProvider>
      </body>
    </html>
  );
}
